# Generated by Django 5.1.1 on 2024-11-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Sales Rep', 'Sales Rep')], max_length=11)),
                ('datejoined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default='pbkdf2_sha256$870000$rvWpGGPefSMqy5mdZDSiCB$W4hcjFuBSZNcj2IRZEj0lKk4JOOgYdtcyv/LSEYh6rc=', max_length=128)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('ordersrc', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Website', 'Website'), ('On premises', 'On premises')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branchid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.branches')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.users')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.DecimalField(decimal_places=0, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('Replace', 'Replace'), ('Refund', 'Refund')], max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branchid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.branches')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.users')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.users')),
            ],
        ),
    ]
