# Generated by Django 5.1.1 on 2024-11-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Lghhn8irHr5wpqoJnLYwS7$J56aFRJ6/RQp7pB5KV/raeR2vnDs7IzgiHY13kgon6Y=', max_length=128),
        ),
    ]
