# Generated by Django 5.1.1 on 2024-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0003_branches_status_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='branch',
            new_name='branchid',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9mzDmf5dDNHOnZMM9hM9xn$q6fc2mvsFalz5tWmIv4NPZtgnOhhJpDmB6E8M1S4fjg=', max_length=128),
        ),
    ]
