# Generated by Django 5.1.1 on 2024-11-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0004_rename_branch_users_branchid_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xBU3abjz0vPtyGBF2Aji8E$H2cBoY7bdW6wPlMQqjIDVVMwo8Cj4sk0DME1oDtuRtg=', max_length=128),
        ),
    ]
