# Generated by Django 5.1.1 on 2024-11-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0005_users_status_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branchid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.branches'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rHbATv5WIZn7wqD8melWhx$ds09MKKzZHFgVEvKfxYQgJYZer874SQecTmEcZ3tgVY=', max_length=128),
        ),
    ]
