# Generated by Django 5.1.1 on 2024-11-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0006_inventory_branchid_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branchid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salestrakav2.branches'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$duYQJN1QiOX34872miCjLI$ksACwBtqooIQOSzAw1NfW+OifyBH37eQtvQBthKDgw0=', max_length=128),
        ),
    ]
