# Generated by Django 5.1.1 on 2024-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0007_alter_inventory_branchid_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='orderid',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xxVGUBJJrBYP4LJ1uRzR6K$HLx2Kw2EF7DKCD64ksSNvbhzYXiM63SMxyrk2QSC4Cw=', max_length=128),
        ),
    ]
