# Generated by Django 5.1.1 on 2024-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0008_alter_sales_orderid_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bCjqpX6UzJuUQfLACgtO2J$pl/h7BKu2FD9moR5uj5WNZBPi7+PXd7b2Ulh5iLAsCY=', max_length=128),
        ),
    ]
