# Generated by Django 5.1.1 on 2024-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0009_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='orderid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$57FWtfPuLagMB5YbPj9vJ9$En9P3CvQe1HLZwJBnThAe9vky1RLPQ0cohh7y4k05nM=', max_length=128),
        ),
    ]
