# Generated by Django 5.1.1 on 2024-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0010_alter_sales_orderid_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_choice',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='returns',
            name='orderid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$4DgC8T1Ds50UZ3OQLQJCmX$+lCpGzDcaRIYpnJ/hNuvHqekdE+4fIQGSRiAOMjLgkY=', max_length=128),
        ),
    ]
