# Generated by Django 5.1.1 on 2024-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0011_sales_payment_choice_alter_returns_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_choice',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gIdhDiRvekS1FtubDGK1ZS$uDVFEyB1zAKlWSYOYslGrYGCyxSlvjcBGn08jhb40jM=', max_length=128),
        ),
    ]
