# Generated by Django 5.1.1 on 2025-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0012_alter_sales_payment_choice_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$QuJ6S6FPv0FJcx3QjU5vgW$uVnrQvh0KCX149NJvGxdJFt5kw0uR9mrA2WMZxSOP0c=', max_length=128),
        ),
    ]
