# Generated by Django 5.1.1 on 2025-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0015_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$cthnQI4f1HAEs9mtQAVsQQ$T7hrGGMMDSWn9YAPHH4i+vSVTvFb1vnzIt+86jdmp1A=', max_length=128),
        ),
    ]
