# Generated by Django 5.1.1 on 2025-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0016_alter_users_is_staff_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gRaa3hyMtqcQJUy7jkN15z$Ur0LlvMQdT9dgr8CupkkQKbqeIHAtp/F5hQcipMoPoM=', max_length=128),
        ),
    ]
