# Generated by Django 5.1.1 on 2025-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0017_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Xgjn2Cd2XlICAdWYN9m27x$TG1dh4abQHoB0n7GCBAvQ6NA9JjTLNLEyXFcxPHMJ94=', max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1),
        ),
    ]
