# Generated by Django 5.1.1 on 2025-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestrakav2', '0018_alter_branches_status_alter_products_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$m3MYhRlOoZmOXb3m5ISItJ$vwXXU8f6HGAJvaD4A3CJDT1RsbioKASExf3fhb/zL7U=', max_length=128),
        ),
    ]
